import { Hero, Intro, Split, Callout, Cards, Button, styles } from '@/components/EditorialPage';
import SustainabilityImpact from '@/components/SustainabilityImpact';
export const metadata = { title: 'Farm to Community Impact — Planet Harvest', description: 'Connecting growers, companies and community organizations to turn fresh food into meaningful action.' };
export default function ImpactPage() {
  return <main id="main-content" className={styles.page}>
    <Hero eyebrow="Farm to community impact" title="Growing Impact." film="impact" copy="Every Planet Harvest program starts with fresh food and ends with impact." image="/impact-hero.jpg" alt="Expansive green farmland at sunrise" tone="green"><Button light href="/contact?interest=community">Make an impact with us</Button></Hero>
    <Intro eyebrow="Connected by a shared purpose" title="Supporting the harvest.<br />Nourishing communities."><p>By connecting our network across growers, produce partners, companies and trusted community organizations, Planet Harvest helps move fresh fruits and vegetables to the people and places where they can make a meaningful difference.</p><p>The result is a model that creates value across the food system: supporting the harvest, expanding access to fresh food and helping our partners create measurable impact in the communities they serve.</p></Intro>
    <Split title="Built around the people you serve." image="/impact-split.jpg" alt="Delivery truck delivering fresh produce to community" eyebrow="Your purpose. Our partnership."><p>Our programs are designed around the unique goals of each partner—from employee wellness and Food as Medicine initiatives to large-scale community distributions and national impact programs.</p><p>We manage the journey from sourcing and box development through logistics, local partnerships, distribution, and impact reporting.</p><Button light href="/food-boxes">Explore our programs</Button></Split>
    <section className={styles.section} id="partners"><div className={styles.sectionHeading}><div><span className={styles.eyebrow}>Putting fresh food to work</span><h2>Partners in<br />meaningful change.</h2></div><p>Connecting people, produce, and purpose through our partner programs.</p></div><div className={styles.partners}><div className={styles.partner}>Eli Lilly</div><div className={styles.partner}>Fresh Communities Tour<span>With Chiquita and Fresh Express</span></div><div className={styles.partner}>On Farm Discoveries<span>Fresh Express</span></div><div className={styles.partner}>Brighter Bites</div><div className={styles.partner}>Families of Conviction</div></div><div style={{marginTop:30}}><Button href="/media">Explore stories in the news</Button></div></section>
    
    <SustainabilityImpact />

    <section className={styles.section}><div className={styles.sectionHeading}><div><span className={styles.eyebrow}>The human impact behind the numbers</span><h2>How we measure<br />meaningful progress.</h2></div><p>Program reporting connects the food we move with the people and communities it reaches.</p></div><Cards items={[{title:'The harvest',copy:'Pounds of produce moved and farmers supported.'},{title:'The community',copy:'Families served, food boxes delivered, and participating community organizations.'},{title:'The partnership',copy:'Corporate partners, employee volunteers, and community engagement.'}]} /></section>
    <Callout title="Fresh food is just the beginning." href="/contact?interest=community" button="Let’s build a partnership" />
  </main>;
}
