import { Hero, Intro, Split, Callout, Cards, Button, styles } from '@/components/EditorialPage';
export const metadata = { title: 'Product Integration & Ingredients — Planet Harvest', description: 'Co-branded, private label, and Planet Harvest products built on scalable, sustainable whole harvest sourcing.' };
export default function ProductsPage() {
  return <main id="main-content" className={styles.page}>
    <Hero eyebrow="What we do / Product integration" title="Food, Reimagined." film="products" copy="We partner with food companies and retailers to bring the best of the harvest to consumers." image="/products-hero.jpg" alt="Packaged fresh produce and ingredients" tone="pink"><Button href="/contact?interest=food-company">Create with us</Button></Hero>
    <Intro eyebrow="Ingredients with possibility" title="Great taste. Whole harvest thinking."><p>By combining innovative product development with scalable, sustainable sourcing, we help our partners deliver delicious, high-quality foods that meet consumer expectations while building a competitive edge in the marketplace.</p><p>Our goal is simple: turn the harvest into products people love while creating value for everyone across the supply chain.</p></Intro>
    <section className={styles.section}><div className={styles.sectionHeading}><div><span className={styles.eyebrow}>Ways to work together</span><h2>Your next product<br />starts here.</h2></div><p>Flexible partnerships that connect fresh ingredients with new possibilities.</p></div><Cards items={[{title:'Co-branded products',copy:'Bring your brand and Planet Harvest together around high-quality foods and sustainable sourcing.'},{title:'Private label',copy:'Create products for your brand, supported by scalable whole harvest sourcing.'},{title:'Planet Harvest branded',copy:'Bring the Planet Harvest approach to consumers through products that celebrate the best of the harvest.'}]} /></section>
    <Split title="The quality people expect. More value from every harvest." image="/products-split.jpg" alt="Fresh produce inspection in manufacturing facility" eyebrow="Built for the marketplace" reverse><p>Delicious, high-quality products that deliver the same taste and quality consumers expect, while building competitive advantage through scalable and whole harvest sourcing.</p><Button href="/sourcing">Explore our sourcing</Button></Split>
    <Callout title="Let’s create something good." copy="Connect with our team to explore ingredients, product development, and partnership opportunities." href="/contact?interest=food-company" button="Start a product partnership" />
  </main>;
}
